FROM node:22-bullseye

# Lazımi native paketlər
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && apt-get clean

WORKDIR /usr/src/app

COPY package*.json ./

# Təmiz və force install
RUN npm install --force

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
